//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public string Pay_ID { get; set; }
        public string Pay_Type { get; set; }
        public Nullable<System.DateTime> Pay_Date { get; set; }
        public Nullable<decimal> Pay_Amount { get; set; }
        public string Cart_ID { get; set; }
        public string Trans_ID { get; set; }
    
        public virtual Cart Cart { get; set; }
    }
}
